/*
  # Seed Items from items.json

  ## Overview
  Populates the items table with all items from the items.json file
  
  ## Changes
  - Inserts 505 items with their default suppliers
  - Sets order_count to 0 for all items
  - Uses ON CONFLICT DO NOTHING to avoid duplicates
  
  ## Notes
  - All items use their assigned supplier from items.json
  - No variants or units are set initially (can be added later via UI)
*/

INSERT INTO items (name, supplier, order_count) VALUES
('4x14', 'KALI', 0),
('6x14 plastic -', 'PISEY', 0),
('Absolut', 'MARKET', 0),
('Almond milk', 'KALI', 0),
('Aluminium', 'KALI', 0),
('Anchovy', 'PISEY', 0),
('Angkor', 'ANGKOR-COMPANY', 0),
('Angkor bt big', 'KALI', 0),
('Apple fruit', 'PISEY', 0),
('Apple juice', 'LEES', 0),
('Aquarius', 'COCA-COMPANY', 0),
('Aubergine', 'PISEY', 0),
('Avocado', 'PISEY', 0),
('Bacardi', 'KALI', 0),
('Bacon', 'KALI', 0),
('Bailey', 'KALI', 0),
('Baking paper', 'MARKET', 0),
('Banana', 'PISEY', 0),
('Banana bread', 'MARKET', 0),
('Bar fish', 'MARKET', 0),
('Bardinet', 'KALI', 0),
('Basil', 'PISEY', 0),
('Bay leaf', 'KALI', 0),
('beef choice short plate -', 'LEES', 0),
('Beef ribeye cube roll ', 'LEES', 0),
('Beef rump', 'LEES', 0),
('Beef striploin', 'MARKET', 0),
('Beefeater', 'MARKET', 0),
('Beetroot', 'PISEY', 0),
('Black bread', 'MARKET', 0),
('Black olives', 'MARKET', 0),
('Black pepper', 'PISEY', 0),
('Black sesame', 'KALI', 0),
('Black tea', 'KALI', 0),
('Blanc 1664', 'MARKET', 0),
('Blue cheese', 'MARKET', 0),
('Blue curacao', 'MARKET', 0),
('Blue sea big', 'STOCK', 0),
('Blue sea small', 'STOCK', 0),
('Bread box', 'TAKEAWAY-SHOP', 0),
('Bread toast', 'MARKET', 0),
('Breadcrumbs', 'PISEY', 0),
('Broccoli', 'PISEY', 0),
('Buckwheat', 'MARKET', 0),
('Bun''s (burger bread)', 'MARKET', 0),
('Burger box', 'PISEY', 0),
('Butter', 'LEES', 0),
('Cabbage', 'PISEY', 0),
('Cake box', 'TAKEAWAY-SHOP', 0),
('Cambodia', 'MARKET', 0),
('Campari', 'MARKET', 0),
('Capers', 'KALI', 0),
('Captain morgan', 'KALI', 0),
('Caramel syrup', 'KOFI', 0),
('Carrots ', 'PISEY', 0),
('Cheddar slice', 'MARKET', 0),
('Cheese slice (Emborg)', 'MARKET', 0),
('Chefwrap plastic', 'MARKET', 0),
('Chicken breast', 'MARKET', 0),
('Chicken leg', 'MARKET', 0),
('Chicken sausage bbq', 'MARKET', 0),
('Chicken wing', 'MARKET', 0),
('Chocolate topping', 'PISEY', 0),
('Chopstick', 'PISEY', 0),
('Coca', 'COCA-COMPANY', 0),
('Coca zero', 'COCA-COMPANY', 0),
('Coconut cream', 'PISEY', 0),
('Coffee oro', 'MARKET', 0),
('Cointreau', 'KALI', 0),
('Cooking cream', 'LEES', 0),
('Cooking oil (5L)', 'PISEY', 0),
('Coriander', 'PISEY', 0),
('Corona', 'MARKET', 0),
('Cottage cheese', 'KALI', 0),
('Crab stick', 'MARKET', 0),
('Cranberry juice', 'LEES', 0),
('Cream cheese', 'MARKET', 0),
('Cucumber', 'PISEY', 0),
('Cucumber long', 'PISEY', 0),
('Cup big 22', 'TAKEAWAY-SHOP', 0),
('Cup coffee 12', 'MARKET', 0),
('Cup small 16', 'TAKEAWAY-SHOP', 0),
('Cutlery set', 'TAKEAWAY-SHOP', 0),
('Dishsoap', 'PISEY', 0),
('Draft keg', 'ANGKOR-COMPANY', 0),
('Dragon fruit', 'PISEY', 0),
('Duck toilet', 'PISEY', 0),
('Dumpling dough', 'MARKET', 0),
('Eggplant', 'PISEY', 0),
('Eggs', 'PISEY', 0),
('Esse', 'KALI', 0),
('Fanta', 'COCA-COMPANY', 0),
('Fish roe', 'PZZA+', 0),
('Fish sauce', 'PISEY', 0),
('Floor cleaner', 'PISEY', 0),
('Flour', 'PISEY', 0),
('Flour 25kg', 'PISEY', 0),
('French fries', 'LEES', 0),
('Fresh milk', 'KALI', 0),
('Frozen strawberries', 'CHARONAI', 0),
('Ganzberg', 'KALI', 0),
('Garlic white', 'PISEY', 0),
('Gherkins', 'PISEY', 0),
('Ginger ale', 'COCA-COMPANY', 0),
('Glass cleaner', 'PISEY', 0),
('Green bell pepper', 'PISEY', 0),
('Green olives', 'KALI', 0),
('Green peas', 'PISEY', 0),
('Green tea', 'MARKET', 0),
('Grenadine', 'MARKET', 0),
('Ham', 'KALI', 0),
('Hand sanitizer', 'PISEY', 0),
('Hand soap', 'PISEY', 0),
('Hand towel napkin', 'PISEY', 0),
('Honey', 'PISEY', 0),
('Iceberg', 'PISEY', 0),
('Indian tenderloin beef', 'LEES', 0),
('Ipa', 'MARKET', 0),
('Jack', 'KALI', 0),
('Jagermeister', 'KALI', 0),
('Jameson', 'KALI', 0),
('Japanese rice', 'MARKET', 0),
('Jasmine tea', 'MARKET', 0),
('Jim beam', 'KALI', 0),
('Jinro', 'MARKET', 0),
('Ketchup big', 'PISEY', 0),
('Khmer soy sauce', 'PISEY', 0),
('Kidney beans', 'PISEY', 0),
('Kikkoman big', 'CHARONAI', 0),
('Knorr cubes', 'PISEY', 0),
('Knorr powder', 'PISEY', 0),
('Lemon', 'PISEY', 0),
('Lemongrass', 'PISEY', 0),
('Lime', 'PISEY', 0),
('Malibu', 'KALI', 0),
('Mandarin', 'PISEY', 0),
('Mango fruit', 'PISEY', 0),
('Mango juice', 'LEES', 0),
('Mayonnaise', 'KALI', 0),
('Mevius', 'KALI', 0),
('Mint', 'PISEY', 0),
('Mozzarella', 'LEES', 0),
('Mushroom fresh', 'PISEY', 0),
('Mushroom can', 'PISEY', 0),
('Mushrooms (brown hat)', 'PISEY', 0),
('Napkin big', 'KALI', 0),
('Napkin small', 'KALI', 0),
('Nutella', 'MARKET', 0),
('Oat milk', 'KALI', 0),
('Olive oil', 'KALI', 0),
('Onion', 'PISEY', 0),
('Onion pickles', 'MARKET', 0),
('Orange fruit', 'PISEY', 0),
('Orange juice', 'LEES', 0),
('Oris', 'KALI', 0),
('Oyster sauce', 'PISEY', 0),
('Papaya rip', 'PISEY', 0),
('Parmesan', 'LEES', 0),
('Parsley', 'PISEY', 0),
('Passion fruit', 'PISEY', 0),
('Pasta box', 'PISEY', 0),
('Peach cream', 'MARKET', 0),
('Peeled tomato', 'PISEY', 0),
('Peepee pads', 'MARKET', 0),
('Pens', 'MARKET', 0),
('Pepperoni', 'KALI', 0),
('Pepsi', 'MARKET', 0),
('Perfume atomizer', 'PISEY', 0),
('Picked spring onion', 'PISEY', 0),
('Pineapple fruit', 'PISEY', 0),
('Pineapple juice', 'MARKET', 0),
('Pink ginger', 'CHARONAI', 0),
('Pizza box', 'MARKET', 0),
('Pizza dough/flour', 'PISEY', 0),
('Plain flour blue', 'PISEY', 0),
('Plastic 12x20', 'PISEY', 0),
('Plastic 8x16', 'PISEY', 0),
('Plastic fork', 'TAKEAWAY-SHOP', 0),
('Plastic spoon', 'PISEY', 0),
('Pork sausage bbq', 'MARKET', 0),
('Pork shoulder bbq', 'MARKET', 0),
('Potato', 'PISEY', 0),
('Printer paper', 'STOCK', 0),
('Puro big', 'ANGKOR-COMPANY', 0),
('Puro small', 'ANGKOR-COMPANY', 0),
('Red bellpepper', 'PISEY', 0),
('Red chilli', 'PISEY', 0),
('Red fish', 'PISEY', 0),
('Red onion', 'PISEY', 0),
('Red wine', 'MARKET', 0),
('Rice', 'PISEY', 0),
('Roman salad', 'PISEY', 0),
('Rosemary', 'MARKET', 0),
('Salmon fish', 'CHARONAI', 0),
('Salt', 'PISEY', 0),
('Sauce box', 'PISEY', 0),
('Seaweed', 'CHARONAI', 0),
('Shallots', 'PISEY', 0),
('Shrimp', 'MARKET', 0),
('Sky blue', 'KALI', 0),
('Smoked chicken sausage', 'MARKET', 0),
('Smoked duck breast', 'LEES', 0),
('Soda', 'COCA-COMPANY', 0),
('Somersby cider', 'MARKET', 0),
('Soup box', 'PISEY', 0),
('Sour cream', 'LEES', 0),
('Spaghetti', 'PISEY', 0),
('Spinach', 'PISEY', 0),
('Sponges', 'PISEY', 0),
('Sprite', 'COCA-COMPANY', 0),
('Squid', 'MARKET', 0),
('Steel sponges', 'PISEY', 0),
('Strapples', 'MARKET', 0),
('Straw big', 'MARKET', 0),
('Straw small', 'MARKET', 0),
('Strawberry', 'MARKET', 0),
('Strawberry ice cream', 'MARKET', 0),
('Sugar', 'PISEY', 0),
('Sugar sachet', 'PISEY', 0),
('Sunlight', 'PISEY', 0),
('Sushi box', 'MARKET', 0),
('Sweet chili sauce', 'PISEY', 0),
('Sweet milk', 'PISEY', 0),
('Sweet milk__1', 'PISEY', 0),
('Tempura flour', 'PISEY', 0),
('Tequila', 'KALI', 0),
('Teryaki sauce', 'CHARONAI', 0),
('Toilet paper roll', 'PISEY', 0),
('Tomato', 'PISEY', 0),
('Tomato paste', 'PISEY', 0),
('Tomato sauce for pizza', 'PISEY', 0),
('Tonic', 'COCA-COMPANY', 0),
('Toothpick', 'TAKEAWAY-SHOP', 0),
('Trash bag', 'PISEY', 0),
('Tuna', 'PISEY', 0),
('Vanilla ice cream', 'MARKET', 0),
('Vanilla syrup', 'MARKET', 0),
('Vinegar (thai)', 'PISEY', 0),
('Vital water', 'MARKET', 0),
('Wasabi', 'MARKET', 0),
('Watermelon', 'PISEY', 0),
('Whipping cream', 'MARKET', 0),
('White fish', 'MARKET', 0),
('White sesame', 'KALI', 0),
('White vinegar (chinese)', 'PISEY', 0),
('White wine', 'MARKET', 0),
('Winston', 'KALI', 0),
('Wrapping film', 'MARKET', 0),
('Yeast', 'PISEY', 0),
('Yellow bellpepper', 'PISEY', 0),
('Yellow noodles', 'PISEY', 0),
('Zuchini', 'PISEY', 0)
ON CONFLICT DO NOTHING;
